#GET localhost:8085/singleton/10

### 1 Bean
GET localhost:8085/singleton/bean/8
###

GET localhost:8085/request/bean/8

### Listen

GET localhost:8085/singleton/8
###


GET localhost:8085/request/8

###

